gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 604800        # Durée de vie du refresh token (ex: 7 jours en secondes)
    ttl_update: true    # Mise à jour du TTL du refresh token à chaque utilisation
    return_expiration: true
    token_parameter_name: refresh_token
    user_provider: 'security.user.provider.concrete.app_user_provider'
