vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            directory_namer: App\Core\Service\Uploader\UserDirectoryNamer
            namer: App\Core\Service\Uploader\CustomNamerUploader
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
