version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/config/php/Dockerfile   # Ce Dockerfile doit être celui pour php:8.3-fpm
      target: php_dev   # ou php_prod selon l'environnement
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - ./:/app:ro           # Le code source en lecture seule
      - var_data:/app/var     # Volume dédié pour le dossier var (pour la persistance et une gestion par Docker)
    # On force l'exécution d'un chown sur /app/var avant de démarrer PHP-FPM
    command: sh -c "chown -R www-data:www-data /app/var && docker-php-entrypoint php-fpm"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./docker/config/php/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./:/app:ro
    ports:
      - "80:80"
      - "443:443"

  database:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql:rw

volumes:
  var_data:
