services:
  php:
    build:
      context: .
      dockerfile: docker/config/php/Dockerfile
      target: php_dev
    volumes:
      - ./:/app
      - ./docker/config/php/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/config/php/conf.d/20-app.dev.ini:/usr/local/etc/php/conf.d/20-app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:latest
    depends_on:
      - database
    # restart: always
    environment:
      PMA_PORT: "3306"
      PMA_HOST: "database"
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 81:80